
[package]
name = "gondola"
version = "0.1.0"
authors = ["Morten H. Solvang <morten.hauke.solvang@gmail.com>"]

[features]
default = []
serialize = ["serde"]

[dependencies]
gondola_derive = { path = "gondola_derive" }
cable_math = { path = "cable_math" }
glutin = "0.8"
gl = "*"
rusttype = "0.2"
bitflags = "0.8"
# Only needed if we want custom serialization derives for color types
serde = { version = "1.0", optional = true }
png = { version = "0.7", features = [] }
