[package]
name = "gondola_vertex_macro"
version = "0.1.0"
authors = ["Morten H. Solvang <morten.hauke.solvang@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.4"
quote = "0.3.12"
gl = "*"

