
[package]
name = "cable_math"
version = "0.1.0"
authors = ["Morten H. Solvang <morten.hauke.solvang@gmail.com>"]

[features]
default = []
serialize = ["serde"]

[dependencies]
num = "0.1.*"
serde = { version = "1.0", optional = true }
